## Table of Contents

* [1. 3D Rigid-Body Motion](#01)
* [2. Homogeneous Transformation](#02)
* [3. Code Examples](#03)
   


## 3D Rigid-Body Motion<a class="anchor" id="01"></a>

![3D_rigid_body](img/03-Coordinate_transformation/3D_rigid_body_motion.png)
Let $p$ denote the vector from the fixed-frame origin to the body-frame origin. In terms of the fixed-frame coordinates, p can be expressed as: 
$$p=p_1\hat{x}_s+p_2\hat{y}_s+p_3\hat{z}_s$$
The axes of the body frame can also be expressed as:
$$\hat{x}_b=r_11\hat{x}_s+r_21\hat{y}_s+r_31\hat{z}_s\\
\hat{y}_b=r_12\hat{x}_s+r_22\hat{y}_s+r_32\hat{z}_s\\
\hat{z}_b=r_13\hat{x}_s+r_23\hat{y}_s+r_33\hat{z}_s$$
Defining $p\in \mathbb{R}^3$ and $R\in \mathbb{R}^{3\times3}$ as: 
$$p=\begin{bmatrix}p_1 \\
                  p_2 \\
                  p_3 \\
   \end{bmatrix}, R=\begin{bmatrix}\hat{x}_b & \hat{y}_b & \hat{z}_b \end{bmatrix}=
   \begin{bmatrix}r_{11} & r_{12} & r_{13}\\
                  r_{21} & r_{22} & r_{23}\\
                  r_{31} & r_{32} & r_{33}\\
                  \end{bmatrix}$$
Since the orientation of a rigid body has three degrees of freedom, only three
of the nine entries in R can be chosen independently. One three-parameter representation of rotations is provided by the exponential coordinates, which define an axis of rotation and the angle rotated about that axis.


## Homogeneous Transformation <a class="anchor" id="02"></a>

In linear algebra, linear transformations can be represented by matrices. If {\displaystyle T}T is a linear transformation mapping ${\displaystyle \mathbb {R} ^{n}}$ to ${\displaystyle \mathbb {R} ^{m}}$ and ${\displaystyle \mathbf {x}}$ is a column vector with ${\displaystyle n}$ entries, then

$${\displaystyle T(\mathbf {x} )=A\mathbf {x} }$$ 
for some ${\displaystyle m\times n}$ matrix ${\displaystyle A}$, called the transformation matrix of ${\displaystyle T}$. Note that ${\displaystyle A}$ has ${\displaystyle m}$ rows and ${\displaystyle n}n$, whereas the transformation ${\displaystyle T}$ is from ${\displaystyle \mathbb {R} ^{n}}$ to ${\displaystyle \mathbb {R} ^{m}}$. There are alternative expressions of transformation matrices involving row vectors that are preferred by some authors.

The homogeneous transformation matices are  $4\times4$ in Euclidean group $SE(3)$ is :

$$T=\begin{bmatrix}R & p \\
                     0 & 1 \\
                     \end{bmatrix}$$
where $R\in SO(3)$ and $p\in \mathbb{R}^3$                  
### Properties of Transformation Matrices
* The inverse of a transformation matrix is also a transformation matrix
$$T^{-1}={\begin{bmatrix}R & p \\
                      0 & 1 \\
                      \end{bmatrix}}^{-1}={\begin{bmatrix}R^T & -R^Tp\\
                                                          0 & 1\end{bmatrix}}$$
* The product of two transformation matrices is also a transformation matrix. 
* The multiplication of transformation matrices is associative but generally not commutative

### Uses of Transformation Matrices
* to represent the configuration (position and orientation) of a rigid body
* to change the reference frame in which a vector or frame is represented; 
* to displace a vector or frame.

## Code Examples<a class="anchor" id="01"></a>
### Example of translation
* Original center of a frame is located at $(0,0,0)$.
* The original frame is translated from $(0,0,0)$ to $(1.3,0,0)$



In [1]:
import open3d as o3d
import copy 
import numpy as np
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
mesh_tx = copy.deepcopy(mesh).translate((1.3, 0, 0))

print('Center of mesh: ', mesh.get_center())
print('Center of mesh tx: ', mesh_tx.get_center())

o3d.visualization.draw_geometries([mesh, mesh_tx])

Center of mesh:  [0.05167549 0.05167549 0.05167549]
Center of mesh tx:  [1.35167549 0.05167549 0.05167549]


* The original frame is translated to $(1.3,1.3,0)$ 

In [2]:
mesh_ty = copy.deepcopy(mesh_tx).translate((0, 1.3, 0))
print('Center of mesh ty: ', mesh_ty.get_center())
o3d.visualization.draw_geometries([mesh, mesh_ty])

Center of mesh ty:  [1.35167549 1.35167549 0.05167549]


### Example of rotation
* Original center of a frame is located at $(0,0,0)$.
* The original frame is translated from $(0,0,0)$ to $90^ {\circ} $ along x-axis.

In [5]:
mesh_r = copy.deepcopy(mesh)
R = mesh.get_rotation_matrix_from_xyz((np.pi / 2, 0, 0))
print(R)
print(type(mesh_r))
mesh_r.rotate(R, center=False)
o3d.visualization.draw_geometries([mesh, mesh_r])

[[ 1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17]]
<class 'open3d.open3d.geometry.TriangleMesh'>


### Example of Scale


In [4]:
mesh_s = copy.deepcopy(mesh).translate((2,0,0))
mesh_s.scale(0.5, center=False)
o3d.visualization.draw_geometries([mesh, mesh_s])