<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc">
    <ul class="toc-item">
        <li>
            <span><a href="#Inverse-Kinematics" data-toc-modified-id="Inverse-Kinematics-1">
            <span class="toc-item-num">1&nbsp;&nbsp;</span>Inverse Kinematics</a></span>
        </li>        
        <li>
            <span><a href="#Analytic-Inverse-Kinematics" data-toc-modified-id="Analytic-Inverse-Kinematics-2">
            <span class="toc-item-num">2&nbsp;&nbsp;</span>Analytic Inverse Kinematics</a></span>
        </li>        
        <li>
            <span><a href="#Numerical-Inverse-Kinematics" data-toc-modified-id="Numerical-Inverse-Kinematics-3">
            <span class="toc-item-num">3&nbsp;&nbsp;</span>Numerical Inverse Kinematics</a></span>
        </li>
    </ul>
</div>

## Inverse Kinematics
*Inverse kinematics* is the mathematical process of calculating the variable joint parameters needed to place the end of a kinematic chain, such as a robot manipulator or animation character's skeleton, in a given position and orientation relative to the start of the chain [[wiki](https://en.wikipedia.org/wiki/Inverse_kinematics)] or in simple worlds, given the position and orientation of the end-effector, find the corresponding joint angles of the robot.
Two method are commonly used in calculation the inverse kinematics: Analytic Inverse Kinematics and Numerical Inverse Kinematics

## Analytic Inverse Kinematics

For a 6R robot, From PoE forward kniematics representation, we can get that $ T = e^{[S_{1}]\theta_{1}}e^{[S_{2}]\theta_{2}}e^{[S_{3}]\theta_{3}}e^{[S_{4}]\theta_{4}}e^{[S_{5}]\theta_{5}}e^{[S_{6}]\theta_{6}}M $. Given some end-effector frame $X$, the inverse kinematics problem is to find solutions $\theta ∈ R_{6}$ satisfying $T(\theta) = X$. The calculation can be calculated using basic trigonometry based on the configuration of the robot, however, this mehod is not accurate enough and sometimes impossible to find a solution for certain configuration of robot.

## Numerical Inverse Kinematics

Iterative numerical methods can be applied if the inverse kinematics equations do not admit analytic solutions. Even in cases where an analytic solution does exist, numerical methods are often used to improve the accuracy of these solutions. The aim is to transform the inverse kinematics equations so that they become amenable to existing numerical methods. 

### Newton–Raphson method

The Newton-Raphson method (also known as Newton's method) is a way to quickly find a good approximation for the root of a real-valued function $g(\theta)=0$. It uses the idea that a continuous and differentiable function can be approximated by a straight line tangent to it.

Suppose you need to find the root of a continuous, differentiable function $g(\theta)$, and you know the root you are looking for is near the point $\theta=\theta^{0}$. Then Newton's method tells us that a better approximation for the root is $\theta^{1} = \theta^{0} - \frac{g(\theta^{0})}{g^{'}(\theta^{0})}$.
This process may be repeated as many times as necessary to get the desired accuracy. In general, for any $\theta$-value $\theta^{k}$, the next value is given by $\theta^{k+1} = \theta^{k} - \frac{g(\theta^{k})}{g^{'}(\theta^{k})}$. 

The same formula applies for the case when $g$ is multi-dimensional, i.e., $g : R^{n} →R^{n}$, in which case
![local image](img/nmr.png)

Note that Newton's method may not work if there are points of inflection, local maxima or minima around $\theta^{0}$ or the root [[Brilliant Math & Science Wiki](https://brilliant.org/wiki/newton-raphson-method/)].

#### Sample code for Newton–Raphson method

In [1]:
# Python3 code for implementation of Newton
# Raphson Method for solving equations
 
# An example function whose solution
# is determined using Bisection Method.
# The function is x^3 - x^2 + 2
def func( x ):
    return x * x * x - x * x + 2
 
# Derivative of the above function
# which is 3*x^x - 2*x
def derivFunc( x ):
    return 3 * x * x - 2 * x
 
# Function to find the root
def newtonRaphson( x ):
    h = func(x) / derivFunc(x)
    while abs(h) >= 0.0001:
        h = func(x)/derivFunc(x)
         
        # x(i+1) = x(i) - f(x) / f'(x)
        x = x - h
     
    print("The value of the root is : ", "%.4f"% x)
 
# Driver program to test above
x0 = -20 # Initial values assumed
newtonRaphson(x0)
 
# This code is contributed by "Sharad_Bhardwaj"

The value of the root is :  -1.0000


### Numerical Inverse Kinematics Algorithm

Suppose we express the end-effector frame using a coordinate vector $x$ governed
by the forward kinematics $x = f(θ)$, a nonlinear vector equation mapping the n
joint coordinates to the m end-effector coordinates. Assume that $f : R^{n}→R^{m}$
is differentiable, and let xd be the desired end-effector coordinates. Then $g(θ)$
for the Newton-Raphson method is defined as $g(θ) = x_{d} −f(θ)$, and the goal is
to find joint coordinates $x_{d}$ such that 
![local image](img/e1.png)


Given an initial guess $θ_{0}$ which is “close to” a solution θd, the kinematics can
be expressed as the Taylor expansion
![local image](img/e2.png)


where $J(θ^{0}) ∈ R^{m×n}$ is the coordinate Jacobian evaluated at $θ^{0}$. Truncating the Taylor expansion at first order, we can approximate the above equation as
![local image](img/e2.png)

Assuming that $J(θ^{0})$ is square $(m = n)$ and invertible, we can solve for $∆θ$ as
![local image](img/e3.png)

If the forward kinematics is linear in $θ$, i.e., the higher-order terms are zero, then the new guess $θ^{1} = θ^{0} + ∆θ $ exactly satisfies $x_{d} = f(θ^{1})$. If the forward kinematics is not linear in $θ$, as is usually the case, the new guess $θ^{1}$ should still be closer to the root than $θ^{0}$, and the process is then repeated,
producing a sequence {$θ^{1}$,$θ^{2}$,$θ^{3}$,...} converging to $θ^{d}$. 

Practical Issues:
1. Use matrix decomposition or optimization methods (least square) instead of computing the inverse of a Jacobian matrix.
2. If the inverse of a Jacobian matrix does not exist, use pseudoinverse.
3. Optimize on configurations (twists) not on transformation matrices (converted to twists).

#### Jacobian Example Code

In [3]:
# Source https://www.quantstart.com/articles/Jacobi-Method-in-Python-and-NumPy/
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot

def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

A = array([[2.0,1.0],[5.0,7.0]])
b = array([11.0,13.0])
guess = array([1.0,1.0])

sol = jacobi(A,b,N=25,x=guess)

print ("A:")
pprint(A)

print ("b:")
pprint(b)

print ("x:")
pprint(sol)


A:
array([[2., 1.],
       [5., 7.]])
b:
array([11., 13.])
x:
array([ 7.11110202, -3.22220342])
